# This is a basic workflow to help you get started with Actions

name: ping

# Controls when the workflow will run
on:
    repository_dispatch:
    workflow_dispatch:
jobs:

  build:
  
    runs-on: windows-2019

    steps:
      - name: Install .NET Desktop Runtime
        run: |
         Invoke-WebRequest -Uri https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-6.0.12-windows-x64-installer -OutFile dotnet-runtime.exe
         Start-Process -FilePath dotnet-runtime.exe -ArgumentList '/install', '/quiet', '/norestart' -Wait
      
      - name: git clone v2rayN
        run: |
          git clone https://github.com/caixye/V2rayN/

      - name: Start v2rayN
        run: |
         ./V2rayN/v2rayN-With-Core/v2rayN.exe
      - name: Ping
        run: |
          ping buyanbuyan.com -t
      - name: Wait 2 hours
        run: node -e "setTimeout(() => {}, 7200000)"
