# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    repository_dispatch:
    workflow_dispatch:
jobs:

  build:
  
    runs-on: windows-2019

    steps:
    
      - name: Install Remote Desktop
        run: |
          Add-WindowsCapability -online -Name RDS-RD-Server -Source windowsfeatures

      - name: Enable Remote Desktop
        run: |
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
      - name: Install curl
        run: |
          Invoke-WebRequest -Uri https://curl.se/windows/dl-8.2.1_4/curl-8.2.1_4-win64-mingw.zip -OutFile curl.zip
          7z x curl.zip -oC:\curl
          Remove-Item curl.zip
          
      - name: Get public IP
        run: |
          $ip = curl http://checkip.dyndns.org
          $ip = $ip.ToString().Split(':')[1].Trim()
          Write-Output "Public IP is: $ip"
      - name: Connect RDP
        run: |
          $ip = curl http://checkip.dyndns.org
          $ip = $ip.ToString().Split(':')[1].Trim() 
          mstsc /v:$ip:3389
      - name: Wait 2 hours
        run: node -e "setTimeout(() => {}, 7200000)"
