# This is a basic workflow to help you get started with Actions

name: two

# Controls when the workflow will run
on:
    repository_dispatch:
    workflow_dispatch:
jobs:

  build:
  
    runs-on: windows-2019

    steps:
    
      - name: Install Remote Desktop
        run: |
          Add-WindowsCapability -online -Name RDS-RD-Server -Source windowsfeatures

      - name: Enable Remote Desktop
        run: |
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
      - name: Install Chocolatey
        run: |
           Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    
      - name: Install ZeroTier One      
        run: |
         choco install zerotier-one -y
         $env:path += ";C:\Program Files (x86)\ZeroTier\One"
         zerotier-cli join d3ecf5726de5303f
         net user Administrator /active:yes
         net user Administrator yu090517
         net localgroup "Remote Desktop Users" Administrator /add
         Set-Service -Name TermService -StartupType Automatic
         Start-Service TermService
         Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
         Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
         Restart-Service TermService
         
      - name: Wait 2 hours
        run: node -e "setTimeout(() => {}, 7200000)"
