# This is a basic workflow to help you get started with Actions

name: two

# Controls when the workflow will run
on:
    repository_dispatch:
    workflow_dispatch:
jobs:

  build:
  
    runs-on: ubuntu-22.04

    steps:
    

            - name: Install DrissionPage
              run: |
                pip install DrissionPage
            - name: Install requests
              run: |
                pip install requests
            - name: clone
              run: |
                git clone https://github.com/caixye/A-chrome
            - name: to directory and run scripts
              run: |
                 cd A-chrome && py main4.py
