# This is a basic workflow to help you get started with Actions

name: two

# Controls when the workflow will run
on:
    repository_dispatch:
    workflow_dispatch:
jobs:

  build:
  
    runs-on: windows-2019

    steps:
    

      - name: Install DrissionPage
        run: |
           pip install DrissionPage
      - name: files in
        run: |
            py main4.py
