# This is a basic workflow to help you get started with Actions

name: two

# Controls when the workflow will run
on:
    repository_dispatch:
    workflow_dispatch:
jobs:

  build:
  
    runs-on: windows-2019

    steps:
            - name: Configure DNS proxy
              run: |
                Write-Host "nameserver 223.5.5.5" | Out-File -FilePath $env:windir\system32\drivers\etc\hosts
                Write-Host "nameserver 8.8.8.8" | Out-File -Append -FilePath $env:windir\system32\drivers\etc\hosts
            - name: Install Chrome
              run: choco install googlechrome
            - name: Install DrissionPage
              run: |
                pip install DrissionPage
            - name: Install requests
              run: |
                pip install requests
            - name: clone
              run: |
                git clone https://github.com/caixye/A-chrome
            - name: to directory and run scripts
              run: |
                 cd A-chrome && python main4.py
